### ISSUE TITLE
[Suggestion] Add support for environment variables

### ISSUE THREAD

**Issue by christianknell** [mrueg/netcupscp-exporter#3]
At the moment you are only able to define the needed parameters (login name, password) via command flag.

For usage in Kubernetes it would be safer to enable the usage of environment variables. This would enable the definition of the parameters as Kubernetes secrets and including them as environment variable into the container.

**Comment by christianknell** [comment]
I could give this a try, if you decide to include this feature.

**Comment by mrueg** [comment]
I'd suggest to use a config-file option instead. I used spf13/pflag initially for quick prototyping. Do you want to add support for it using https://github.com/spf13/viper or https://github.com/alecthomas/kong?

**Comment by christianknell** [comment]
So you mean a flag --config-file? Should this flag override the login-name and password flag? Or do these flags override the values given from the config-file?

I haven't programmed in golang yet, but i will give it a try.

**Comment by mrueg** [comment]
You can now use environment variables with v0.2.0
See also: https://github.com/mrueg/netcupscp-exporter/commit/5c5dfb05c49dc8a6270efb84689a7b33d91a7f15

**Comment by christianknell** [comment]
works perfect. Thanks a lot. I have updated the Helm Chart to use Environment variables now: https://artifacthub.io/packages/helm/christianknell/netcupscp-exporter/1.0.2
