### ISSUE TITLE
[Suggestion] Provide a grafana dashboard

### ISSUE THREAD

**Issue by christianknell** [mrueg/netcupscp-exporter#4]
For simplification, it would be great if you could provide a Grafana dashboard. This would make using the exporter much easier.

**Comment by mrueg** [comment]
Feel free to PR one (+ a screenshot ideally), if you have one.
Except for disk space and network traffic, the exporter does not provide a lot of information that can be used for active monitoring. The other exported metrics are discovery data and can be used to enrich other dashboards.

**Comment by christianknell** [comment]
I have published one Dashboard here: https://grafana.com/grafana/dashboards/16705
