### ISSUE TITLE
Error with attached Failover-IPv4 /Failover IPv6-Subnet

### ISSUE THREAD

**Issue by eifelmicha** [mrueg/netcupscp-exporter#8]
Thanks for providing this exporter. I ran into an issue after deploying the 0.2 version. When trying to fetch values from the metrics endpoint all i can see is the following:

---
An error has occurred while serving metrics:

3 error(s) occurred:
* collected metric "scp_interface_throttled" { label:<name:"driver" value:"virtio" > label:<name:"id" value:"5c069acd57414f2e996328e5f75807eb" > label:<name:"ip" value:"45.90.X.XXX" > label:<name:"ip_type" value:"ipv4" > label:<name:"mac" value:"00:00:00:00:00:00" > label:<name:"throttle_message" value:"" > label:<name:"vserver" value:"v22YYYY" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "scp_interface_throttled" { label:<name:"driver" value:"virtio" > label:<name:"id" value:"5c069acd57414f2e996328e5f75807eb" > label:<name:"ip" value:"2a03:4000:X:X::/64" > label:<name:"ip_type" value:"ipv6" > label:<name:"mac" value:"00:00:00:00:00:00" > label:<name:"throttle_message" value:"" > label:<name:"vserver" value:"v22YYYY" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "scp_interface_throttled" { label:<name:"driver" value:"virtio" > label:<name:"id" value:"3897dbecefd7c0d21cf7fc3145143909" > label:<name:"ip" value:"2a03:4000:X:X::/64" > label:<name:"ip_type" value:"ipv6" > label:<name:"mac" value:"00:00:00:00:00:00" > label:<name:"throttle_message" value:"" > label:<name:"vserver" value:"v22YYYY" > gauge:<value:0 > } was collected before with the same name and label values
---

I have a few Failover IPs / Subnets with Netcup.

The Mac Adress and vServer values are obfuscated by purpose. As soon as i detach the IPs / Subnet from the Servers, they are not appearing anymore in the error output. However i can't detach all since then my service would be down.

**Comment by mrueg** [comment]
Thanks for letting me know. 
I don't use failover IPs or an advanced configuration with netcup, so it could be your SCP returns different information that I did not include in the exporter.

I've added support for a debug log-level in v0.2.1  can you run the exporter with `--log-level=debug`? The log output should show the XML it receives. It would be great if you could share it with and without failover, so I can compare the output.

**Comment by eifelmicha** [comment]
I just did and send you the outputs via Email. Hops this is OK so i don't need to obfuscate all the important things ;-)

**Comment by mrueg** [comment]
Thanks! I can see the issue now, that it can include multiple ip blocks and the failover IP gets added twice.

**Comment by eifelmicha** [comment]
Great, I'm happy to help and just ran the 0.2.2 Tag. No more error message.

**Comment by mrueg** [comment]
Thanks for testing!
